language: go

services:
  - docker

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

script:
  - make lint
  - make test-unit
  - make build-linux
  - make docker
  - make test-end
