#
# Run progress with a postgres instance in dev environment.
#

version: '3'
services:
  progress:
    container_name: progress
    image: hoanhan101/progress
    ports:
    - '8000:8000'

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
